volumes:
  pg_data:
    driver: local

x-base:
  &base-backend
  stdin_open: true
  tty: true
  env_file:
    - .env
  depends_on:
    - redis
  volumes:
    - .:/app
    - ./data:/data

services:


  redis:
    image: redis:latest
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - "6379:6379"

  backend:
    <<: *base-backend
    build:
      context: .
    command: gunicorn -k uvicorn.workers.UvicornWorker -c gunicorn-conf.py --timeout 60 server:app
    ports:
        - "4000:4000"