"""add_forecast

Revision ID: 7138745372b6
Revises: 303c5aed34bd
Create Date: 2026-03-06 17:02:20.569141

"""

from typing import Sequence
from typing import Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7138745372b6'
down_revision: Union[str, Sequence[str], None] = '303c5aed34bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('weathers', sa.Column('hours_forecast', sa.Integer(), nullable=False))
    op.create_index('ix_weathers_created_city_days', 'weathers', ['created_at', 'city', 'hours_forecast'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_weathers_created_city_days', table_name='weathers')
    op.drop_column('weathers', 'hours_forecast')
    # ### end Alembic commands ###
