"""add_performance

Revision ID: 303c5aed34bd
Revises: e6655f08a77d
Create Date: 2026-03-05 16:11:37.025041

"""

from typing import Sequence
from typing import Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '303c5aed34bd'
down_revision: Union[str, Sequence[str], None] = 'e6655f08a77d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_weathers_city'), 'weathers', ['city'], unique=False)
    op.create_index(op.f('ix_weathers_created_at'), 'weathers', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weathers_created_at'), table_name='weathers')
    op.drop_index(op.f('ix_weathers_city'), table_name='weathers')
    # ### end Alembic commands ###
