name: Run unit tests

on:
  pull_request:
  push:
    branches:
    - main

jobs:
  run-tests:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      checks: write
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Make env file
        run: mv .env.example .env

      - name: Run tests
        run: bash bin/test --junitxml=test_report.xml

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always() && github.actor != 'dependabot[bot]'
        with:
          files: |
            test_report.xml
